"""add family genealogy relationships marriages and branches

Revision ID: 5d2e2773f337
Revises: 0b7037430e5d
Create Date: 2026-09-07 22:50:32.685400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d2e2773f337'
down_revision: Union[str, Sequence[str], None] = '0b7037430e5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('family_branches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('founding_member_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['founding_member_id'], ['family_members.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_family_branches_founding_member_id'), 'family_branches', ['founding_member_id'], unique=False)
    op.create_index(op.f('ix_family_branches_is_active'), 'family_branches', ['is_active'], unique=False)
    op.create_index(op.f('ix_family_branches_name'), 'family_branches', ['name'], unique=True)
    op.create_table('family_relationships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=False),
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.Enum('FATHER', 'MOTHER', 'GUARDIAN', name='family_relationship_type'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('parent_id <> child_id', name='ck_family_relationships_not_self_parent'),
    sa.ForeignKeyConstraint(['child_id'], ['family_members.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['parent_id'], ['family_members.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_id', 'child_id', name='uq_family_relationships_parent_child')
    )
    op.create_index(op.f('ix_family_relationships_child_id'), 'family_relationships', ['child_id'], unique=False)
    op.create_index('ix_family_relationships_parent_child', 'family_relationships', ['parent_id', 'child_id'], unique=False)
    op.create_index(op.f('ix_family_relationships_parent_id'), 'family_relationships', ['parent_id'], unique=False)
    op.create_index(op.f('ix_family_relationships_relationship_type'), 'family_relationships', ['relationship_type'], unique=False)
    op.create_table('marriages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('spouse_one_id', sa.UUID(), nullable=False),
    sa.Column('spouse_two_id', sa.UUID(), nullable=False),
    sa.Column('marriage_date', sa.Date(), nullable=True),
    sa.Column('marriage_location', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('MARRIED', 'SEPARATED', 'DIVORCED', 'WIDOWED', name='marriage_status_type'), server_default='MARRIED', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('spouse_one_id <> spouse_two_id', name='ck_marriages_different_spouses'),
    sa.ForeignKeyConstraint(['spouse_one_id'], ['family_members.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['spouse_two_id'], ['family_members.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marriages_spouse_one_id'), 'marriages', ['spouse_one_id'], unique=False)
    op.create_index(op.f('ix_marriages_spouse_two_id'), 'marriages', ['spouse_two_id'], unique=False)
    op.create_index('ix_marriages_spouses', 'marriages', ['spouse_one_id', 'spouse_two_id'], unique=False)
    op.create_index(op.f('ix_marriages_status'), 'marriages', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_marriages_status'), table_name='marriages')
    op.drop_index('ix_marriages_spouses', table_name='marriages')
    op.drop_index(op.f('ix_marriages_spouse_two_id'), table_name='marriages')
    op.drop_index(op.f('ix_marriages_spouse_one_id'), table_name='marriages')
    op.drop_table('marriages')
    op.drop_index(op.f('ix_family_relationships_relationship_type'), table_name='family_relationships')
    op.drop_index(op.f('ix_family_relationships_parent_id'), table_name='family_relationships')
    op.drop_index('ix_family_relationships_parent_child', table_name='family_relationships')
    op.drop_index(op.f('ix_family_relationships_child_id'), table_name='family_relationships')
    op.drop_table('family_relationships')
    op.drop_index(op.f('ix_family_branches_name'), table_name='family_branches')
    op.drop_index(op.f('ix_family_branches_is_active'), table_name='family_branches')
    op.drop_index(op.f('ix_family_branches_founding_member_id'), table_name='family_branches')
    op.drop_table('family_branches')
    # ### end Alembic commands ###
