"""add meetings and attendance management

Revision ID: 6dd251ef35d1
Revises: a5809cdf9cef
Create Date: 2026-09-07 23:11:30.413859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6dd251ef35d1'
down_revision: Union[str, Sequence[str], None] = 'a5809cdf9cef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meetings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('meeting_number', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('meeting_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('venue', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('meeting_type', sa.Enum('GENERAL', 'ANNUAL', 'EMERGENCY', 'SPECIAL', 'OTHER', name='meeting_type_enum'), server_default='GENERAL', nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'ONGOING', 'COMPLETED', 'CANCELLED', name='meeting_status_enum'), server_default='SCHEDULED', nullable=False),
    sa.Column('chairperson_id', sa.UUID(), nullable=True),
    sa.Column('secretary_id', sa.UUID(), nullable=True),
    sa.Column('agenda', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chairperson_id'], ['family_members.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['secretary_id'], ['family_members.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meetings_chairperson_id'), 'meetings', ['chairperson_id'], unique=False)
    op.create_index(op.f('ix_meetings_created_by'), 'meetings', ['created_by'], unique=False)
    op.create_index('ix_meetings_date_status', 'meetings', ['meeting_date', 'status'], unique=False)
    op.create_index(op.f('ix_meetings_location'), 'meetings', ['location'], unique=False)
    op.create_index(op.f('ix_meetings_meeting_date'), 'meetings', ['meeting_date'], unique=False)
    op.create_index(op.f('ix_meetings_meeting_number'), 'meetings', ['meeting_number'], unique=True)
    op.create_index(op.f('ix_meetings_meeting_type'), 'meetings', ['meeting_type'], unique=False)
    op.create_index(op.f('ix_meetings_secretary_id'), 'meetings', ['secretary_id'], unique=False)
    op.create_index(op.f('ix_meetings_status'), 'meetings', ['status'], unique=False)
    op.create_index(op.f('ix_meetings_title'), 'meetings', ['title'], unique=False)
    op.create_table('attendance',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.Column('family_member_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PRESENT', 'ABSENT', 'PERMISSION', 'LATE', 'EXCUSED', name='attendance_status_enum'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('arrival_time', sa.Time(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('recorded_by', sa.UUID(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['family_member_id'], ['family_members.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_id', 'family_member_id', name='uq_attendance_meeting_member')
    )
    op.create_index(op.f('ix_attendance_family_member_id'), 'attendance', ['family_member_id'], unique=False)
    op.create_index(op.f('ix_attendance_meeting_id'), 'attendance', ['meeting_id'], unique=False)
    op.create_index('ix_attendance_meeting_status', 'attendance', ['meeting_id', 'status'], unique=False)
    op.create_index('ix_attendance_member_status', 'attendance', ['family_member_id', 'status'], unique=False)
    op.create_index(op.f('ix_attendance_recorded_by'), 'attendance', ['recorded_by'], unique=False)
    op.create_index(op.f('ix_attendance_status'), 'attendance', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attendance_status'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_recorded_by'), table_name='attendance')
    op.drop_index('ix_attendance_member_status', table_name='attendance')
    op.drop_index('ix_attendance_meeting_status', table_name='attendance')
    op.drop_index(op.f('ix_attendance_meeting_id'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_family_member_id'), table_name='attendance')
    op.drop_table('attendance')
    op.drop_index(op.f('ix_meetings_title'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_status'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_secretary_id'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_meeting_type'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_meeting_number'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_meeting_date'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_location'), table_name='meetings')
    op.drop_index('ix_meetings_date_status', table_name='meetings')
    op.drop_index(op.f('ix_meetings_created_by'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_chairperson_id'), table_name='meetings')
    op.drop_table('meetings')
    # ### end Alembic commands ###
