"""add contribution management database models

Revision ID: 9b2535e92a8b
Revises: 6dd251ef35d1
Create Date: 2026-09-07 23:42:53.659260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b2535e92a8b'
down_revision: Union[str, Sequence[str], None] = '6dd251ef35d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contribution_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('default_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('frequency', sa.Enum('ANNUAL', 'ONE_TIME', 'MONTHLY', 'OTHER', name='contribution_frequency_enum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("default_amount >= 0 AND default_amount <> 'NaN'::numeric", name='ck_contribution_types_amount'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_contribution_types_created_by', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_contribution_types_name')
    )
    op.create_index(op.f('ix_contribution_types_created_by'), 'contribution_types', ['created_by'], unique=False)
    op.create_index(op.f('ix_contribution_types_is_active'), 'contribution_types', ['is_active'], unique=False)
    op.create_table('contribution_periods',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contribution_type_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('amount_per_member', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'CLOSED', name='contribution_period_status_enum'), server_default='DRAFT', nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("amount_per_member >= 0 AND amount_per_member <> 'NaN'::numeric", name='ck_contribution_periods_amount'),
    sa.CheckConstraint('due_date >= start_date', name='ck_contribution_periods_dates'),
    sa.ForeignKeyConstraint(['contribution_type_id'], ['contribution_types.id'], name='fk_contribution_periods_contribution_type_id', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_contribution_periods_created_by', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contribution_periods_contribution_type_id'), 'contribution_periods', ['contribution_type_id'], unique=False)
    op.create_index(op.f('ix_contribution_periods_created_by'), 'contribution_periods', ['created_by'], unique=False)
    op.create_index('ix_contribution_periods_type_status', 'contribution_periods', ['contribution_type_id', 'status'], unique=False)
    op.create_table('member_contributions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contribution_period_id', sa.UUID(), nullable=False),
    sa.Column('family_member_id', sa.UUID(), nullable=False),
    sa.Column('amount_due', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('UNPAID', 'PARTIALLY_PAID', 'PAID', name='contribution_status_enum'), server_default='UNPAID', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("amount_due >= 0 AND amount_due <> 'NaN'::numeric", name='ck_member_contributions_amount'),
    sa.ForeignKeyConstraint(['contribution_period_id'], ['contribution_periods.id'], name='fk_member_contributions_contribution_period_id', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['family_member_id'], ['family_members.id'], name='fk_member_contributions_family_member_id', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contribution_period_id', 'family_member_id', name='uq_member_contributions_period_member')
    )
    op.create_index(op.f('ix_member_contributions_contribution_period_id'), 'member_contributions', ['contribution_period_id'], unique=False)
    op.create_index(op.f('ix_member_contributions_family_member_id'), 'member_contributions', ['family_member_id'], unique=False)
    op.create_index('ix_member_contributions_period_status', 'member_contributions', ['contribution_period_id', 'status'], unique=False)
    op.create_table('contribution_payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('member_contribution_id', sa.UUID(), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('payment_method', sa.Enum('CASH', 'MOBILE_MONEY', 'BANK_TRANSFER', 'CHEQUE', 'OTHER', name='contribution_payment_method_enum'), nullable=False),
    sa.Column('reference', sa.String(length=150), nullable=True),
    sa.Column('receipt_number', sa.String(length=80), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('received_by', sa.UUID(), nullable=True),
    sa.Column('recorded_by', sa.UUID(), nullable=True),
    sa.Column('is_reversed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('reversed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reversed_by', sa.UUID(), nullable=True),
    sa.Column('reversal_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("amount_paid > 0 AND amount_paid <> 'NaN'::numeric", name='ck_contribution_payments_amount'),
    sa.CheckConstraint('(is_reversed = false AND reversed_at IS NULL AND reversed_by IS NULL AND reversal_reason IS NULL) OR (is_reversed = true AND reversed_at IS NOT NULL AND reversed_by IS NOT NULL AND reversal_reason IS NOT NULL AND length(trim(reversal_reason)) > 0)', name='ck_contribution_payments_reversal'),
    sa.ForeignKeyConstraint(['member_contribution_id'], ['member_contributions.id'], name='fk_contribution_payments_member_contribution_id', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['received_by'], ['users.id'], name='fk_contribution_payments_received_by', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], name='fk_contribution_payments_recorded_by', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reversed_by'], ['users.id'], name='fk_contribution_payments_reversed_by', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('receipt_number', name='uq_contribution_payments_receipt')
    )
    op.create_index(op.f('ix_contribution_payments_member_contribution_id'), 'contribution_payments', ['member_contribution_id'], unique=False)
    op.create_index('ix_contribution_payments_obligation_reversed', 'contribution_payments', ['member_contribution_id', 'is_reversed'], unique=False)
    op.create_index(op.f('ix_contribution_payments_payment_date'), 'contribution_payments', ['payment_date'], unique=False)
    op.create_index(op.f('ix_contribution_payments_received_by'), 'contribution_payments', ['received_by'], unique=False)
    op.create_index(op.f('ix_contribution_payments_recorded_by'), 'contribution_payments', ['recorded_by'], unique=False)
    op.create_index(op.f('ix_contribution_payments_reversed_by'), 'contribution_payments', ['reversed_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contribution_payments_reversed_by'), table_name='contribution_payments')
    op.drop_index(op.f('ix_contribution_payments_recorded_by'), table_name='contribution_payments')
    op.drop_index(op.f('ix_contribution_payments_received_by'), table_name='contribution_payments')
    op.drop_index(op.f('ix_contribution_payments_payment_date'), table_name='contribution_payments')
    op.drop_index('ix_contribution_payments_obligation_reversed', table_name='contribution_payments')
    op.drop_index(op.f('ix_contribution_payments_member_contribution_id'), table_name='contribution_payments')
    op.drop_table('contribution_payments')
    op.drop_index('ix_member_contributions_period_status', table_name='member_contributions')
    op.drop_index(op.f('ix_member_contributions_family_member_id'), table_name='member_contributions')
    op.drop_index(op.f('ix_member_contributions_contribution_period_id'), table_name='member_contributions')
    op.drop_table('member_contributions')
    op.drop_index('ix_contribution_periods_type_status', table_name='contribution_periods')
    op.drop_index(op.f('ix_contribution_periods_created_by'), table_name='contribution_periods')
    op.drop_index(op.f('ix_contribution_periods_contribution_type_id'), table_name='contribution_periods')
    op.drop_table('contribution_periods')
    op.drop_index(op.f('ix_contribution_types_is_active'), table_name='contribution_types')
    op.drop_index(op.f('ix_contribution_types_created_by'), table_name='contribution_types')
    op.drop_table('contribution_types')
    # ### end Alembic commands ###

    # PostgreSQL enum types outlive their tables unless explicitly dropped.
    sa.Enum(name="contribution_payment_method_enum").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="contribution_status_enum").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="contribution_period_status_enum").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="contribution_frequency_enum").drop(op.get_bind(), checkfirst=True)
