"""add family genealogy relationships marriages and branches

Revision ID: a5809cdf9cef
Revises: 5d2e2773f337
Create Date: 2026-09-07 22:59:42.780200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5809cdf9cef'
down_revision: Union[str, Sequence[str], None] = '5d2e2773f337'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
