"""create authentication and family member foundation

Revision ID: a91dd37431ed
Revises: 
Create Date: 2026-09-07 22:05:34.211897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a91dd37431ed'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('family_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('family_number', sa.String(length=30), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('sex', sa.Enum('MALE', 'FEMALE', name='sex_type'), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('phone_number', sa.String(length=30), nullable=True),
    sa.Column('current_residence', sa.String(length=255), nullable=True),
    sa.Column('marital_status', sa.Enum('SINGLE', 'MARRIED', 'SEPARATED', 'DIVORCED', 'WIDOWED', name='marital_status_type'), server_default='SINGLE', nullable=False),
    sa.Column('living_status', sa.Enum('LIVING', 'DECEASED', 'UNKNOWN', name='living_status_type'), server_default='LIVING', nullable=False),
    sa.Column('date_of_death', sa.Date(), nullable=True),
    sa.Column('profile_image_path', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('date_of_death IS NULL OR date_of_birth IS NULL OR date_of_death >= date_of_birth', name='ck_family_members_death_after_birth'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_family_members_current_residence'), 'family_members', ['current_residence'], unique=False)
    op.create_index(op.f('ix_family_members_family_number'), 'family_members', ['family_number'], unique=True)
    op.create_index(op.f('ix_family_members_first_name'), 'family_members', ['first_name'], unique=False)
    op.create_index('ix_family_members_full_name', 'family_members', ['last_name', 'first_name', 'middle_name'], unique=False)
    op.create_index(op.f('ix_family_members_is_active'), 'family_members', ['is_active'], unique=False)
    op.create_index(op.f('ix_family_members_last_name'), 'family_members', ['last_name'], unique=False)
    op.create_index(op.f('ix_family_members_living_status'), 'family_members', ['living_status'], unique=False)
    op.create_index(op.f('ix_family_members_marital_status'), 'family_members', ['marital_status'], unique=False)
    op.create_index(op.f('ix_family_members_phone_number'), 'family_members', ['phone_number'], unique=False)
    op.create_index(op.f('ix_family_members_sex'), 'family_members', ['sex'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('family_member_id', sa.UUID(), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'ADMIN', name='user_role_type'), server_default='ADMIN', nullable=False),
    sa.Column('totp_secret_encrypted', sa.Text(), nullable=True),
    sa.Column('totp_enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('authenticator_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('failed_login_attempts >= 0', name='ck_users_failed_login_attempts_non_negative'),
    sa.ForeignKeyConstraint(['family_member_id'], ['family_members.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_family_member_id'), 'users', ['family_member_id'], unique=True)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('login_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('attempted_identifier', sa.String(length=255), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('computer_name', sa.String(length=255), nullable=True),
    sa.Column('login_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('logout_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('logout_at IS NULL OR logout_at >= login_at', name='ck_login_history_logout_after_login'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_history_attempted_identifier'), 'login_history', ['attempted_identifier'], unique=False)
    op.create_index(op.f('ix_login_history_login_at'), 'login_history', ['login_at'], unique=False)
    op.create_index(op.f('ix_login_history_success'), 'login_history', ['success'], unique=False)
    op.create_index(op.f('ix_login_history_user_id'), 'login_history', ['user_id'], unique=False)
    op.create_table('recovery_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('is_used', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'code_hash', name='uq_recovery_codes_user_code_hash')
    )
    op.create_index(op.f('ix_recovery_codes_is_used'), 'recovery_codes', ['is_used'], unique=False)
    op.create_index(op.f('ix_recovery_codes_user_id'), 'recovery_codes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recovery_codes_user_id'), table_name='recovery_codes')
    op.drop_index(op.f('ix_recovery_codes_is_used'), table_name='recovery_codes')
    op.drop_table('recovery_codes')
    op.drop_index(op.f('ix_login_history_user_id'), table_name='login_history')
    op.drop_index(op.f('ix_login_history_success'), table_name='login_history')
    op.drop_index(op.f('ix_login_history_login_at'), table_name='login_history')
    op.drop_index(op.f('ix_login_history_attempted_identifier'), table_name='login_history')
    op.drop_table('login_history')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_family_member_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_family_members_sex'), table_name='family_members')
    op.drop_index(op.f('ix_family_members_phone_number'), table_name='family_members')
    op.drop_index(op.f('ix_family_members_marital_status'), table_name='family_members')
    op.drop_index(op.f('ix_family_members_living_status'), table_name='family_members')
    op.drop_index(op.f('ix_family_members_last_name'), table_name='family_members')
    op.drop_index(op.f('ix_family_members_is_active'), table_name='family_members')
    op.drop_index('ix_family_members_full_name', table_name='family_members')
    op.drop_index(op.f('ix_family_members_first_name'), table_name='family_members')
    op.drop_index(op.f('ix_family_members_family_number'), table_name='family_members')
    op.drop_index(op.f('ix_family_members_current_residence'), table_name='family_members')
    op.drop_table('family_members')
    # ### end Alembic commands ###
