"""add member affiliation and union child order

Revision ID: c637915b29fc
Revises: 474a79f1f1db
Create Date: 2026-09-08 13:18:29.229066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c637915b29fc'
down_revision: Union[str, Sequence[str], None] = '474a79f1f1db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    sa.Enum("LINEAGE_MEMBER", "MARRIED_IN", name="family_affiliation_type").create(op.get_bind(), checkfirst=True)
    op.create_table('marriage_children',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('marriage_id', sa.UUID(), nullable=False),
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('birth_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('birth_order > 0', name='ck_marriage_children_positive'),
    sa.ForeignKeyConstraint(['child_id'], ['family_members.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['marriage_id'], ['marriages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('marriage_id', 'birth_order', name='uq_marriage_children_order'),
    sa.UniqueConstraint('marriage_id', 'child_id', name='uq_marriage_children_child')
    )
    op.create_index(op.f('ix_marriage_children_child_id'), 'marriage_children', ['child_id'], unique=False)
    op.create_index(op.f('ix_marriage_children_marriage_id'), 'marriage_children', ['marriage_id'], unique=False)
    op.add_column('family_members', sa.Column('affiliation_type', sa.Enum('LINEAGE_MEMBER', 'MARRIED_IN', name='family_affiliation_type'), server_default='LINEAGE_MEMBER', nullable=False))
    op.create_index(op.f('ix_family_members_affiliation_type'), 'family_members', ['affiliation_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_family_members_affiliation_type'), table_name='family_members')
    op.drop_column('family_members', 'affiliation_type')
    op.drop_index(op.f('ix_marriage_children_marriage_id'), table_name='marriage_children')
    op.drop_index(op.f('ix_marriage_children_child_id'), table_name='marriage_children')
    op.drop_table('marriage_children')
    sa.Enum(name="family_affiliation_type").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
