"""add gallery and family history models

Revision ID: cd0623e5d4ce
Revises: 9b2535e92a8b
Create Date: 2026-09-08 00:07:54.696030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd0623e5d4ce'
down_revision: Union[str, Sequence[str], None] = '9b2535e92a8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('family_history',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('historical_period', sa.String(length=150), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_family_history_creator', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_family_history_title'), 'family_history', ['title'], unique=False)
    op.create_table('gallery_albums',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('cover_image_path', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_gallery_albums_creator', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gallery_albums_created_by'), 'gallery_albums', ['created_by'], unique=False)
    op.create_index(op.f('ix_gallery_albums_title'), 'gallery_albums', ['title'], unique=False)
    op.create_table('gallery_items',
    sa.Column('album_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['gallery_albums.id'], name='fk_gallery_items_album', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name='fk_gallery_items_uploader', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gallery_items_album_id'), 'gallery_items', ['album_id'], unique=False)
    op.create_table('history_media',
    sa.Column('family_history_id', sa.UUID(), nullable=False),
    sa.Column('media_type', sa.Enum('IMAGE', 'VIDEO', 'DOCUMENT', 'AUDIO', name='history_media_type_enum'), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['family_history_id'], ['family_history.id'], name='fk_history_media_history', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name='fk_history_media_uploader', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_history_media_family_history_id'), 'history_media', ['family_history_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_history_media_family_history_id'), table_name='history_media')
    op.drop_table('history_media')
    op.drop_index(op.f('ix_gallery_items_album_id'), table_name='gallery_items')
    op.drop_table('gallery_items')
    op.drop_index(op.f('ix_gallery_albums_title'), table_name='gallery_albums')
    op.drop_index(op.f('ix_gallery_albums_created_by'), table_name='gallery_albums')
    op.drop_table('gallery_albums')
    op.drop_index(op.f('ix_family_history_title'), table_name='family_history')
    op.drop_table('family_history')
    # ### end Alembic commands ###

    sa.Enum(name="history_media_type_enum").drop(op.get_bind(), checkfirst=True)
